"use client";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import { UploadZone } from "@/components/documents/upload-zone";

type Taxonomy = { categories: { id:string;name:string }[]; universities: { id:string;name:string;faculties:{id:string;name:string;departments:{id:string;name:string}[]}[] }[] };
export function MetadataForm({ taxonomy }: { taxonomy: Taxonomy }) {
  const router=useRouter(); const [file,setFile]=useState<File>(); const [university,setUniversity]=useState(""); const [faculty,setFaculty]=useState(""); const [error,setError]=useState(""); const [progress,setProgress]=useState("");
  const faculties=taxonomy.universities.find((item)=>item.id===university)?.faculties??[]; const departments=faculties.find((item)=>item.id===faculty)?.departments??[];
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!file)return setError("Sélectionnez un fichier.");setError("");setProgress("Préparation sécurisée…");const form=new FormData(event.currentTarget);const checksum=await sha256(file);const payload={...Object.fromEntries(form),universityId:university||null,facultyId:faculty||null,departmentId:String(form.get("departmentId")||"")||null,keywords:String(form.get("keywords")).split(",").map(v=>v.trim()).filter(Boolean),mimeType:file.type,fileName:file.name,sizeBytes:file.size,checksum};const created=await fetch("/api/documents/upload",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await created.json() as {error?:string;uploadUrl?:string;fileId?:string;documentId?:string};if(!created.ok||!result.uploadUrl||!result.fileId)return setError(result.error??"Création impossible.");setProgress("Transfert chiffré vers Google Cloud…");const uploaded=await fetch(result.uploadUrl,{method:"PUT",headers:{"Content-Type":file.type},body:file});if(!uploaded.ok)return setError("Le transfert du fichier a échoué.");setProgress("Vérification du fichier…");const confirmed=await fetch("/api/documents/upload",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({fileId:result.fileId})});if(!confirmed.ok)return setError("Le fichier transféré n’a pas pu être confirmé.");router.push(`/documents/${result.documentId}`);router.refresh();}
  return <form className="metadata-form glass card" onSubmit={submit}><UploadZone onFile={setFile}/>{error&&<p className="form-error" role="alert">{error}</p>}{progress&&<p className="form-success" role="status">{progress}</p>}<div className="form-grid"><label>Titre<input className="input" name="title" required minLength={5}/></label><label>Type<select className="input" name="type" required>{["TFC","MEMOIRE","THESE","ARTICLE","RAPPORT"].map(v=><option key={v}>{v}</option>)}</select></label><label className="span-2">Résumé<textarea className="input textarea" name="abstract" required minLength={20}/></label><label>Université<select className="input" value={university} onChange={e=>{setUniversity(e.target.value);setFaculty("");}}><option value="">Indépendant</option>{taxonomy.universities.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select></label><label>Faculté<select className="input" value={faculty} onChange={e=>setFaculty(e.target.value)}><option value="">—</option>{faculties.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select></label><label>Département<select className="input" name="departmentId"><option value="">—</option>{departments.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select></label><label>Catégorie<select className="input" name="categoryId" required><option value="">Choisir</option>{taxonomy.categories.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select></label><label>Promotion<input className="input" name="promotion"/></label><label>Année académique<input className="input" name="academicYear" placeholder="2025-2026" pattern="[0-9]{4}-[0-9]{4}" required/></label><label>Année<input className="input" name="year" type="number" min="1800" max={new Date().getFullYear()+1} required/></label><label>Langue<input className="input" name="language" defaultValue="fr" required/></label><label>Licence<input className="input" name="license" defaultValue="CC BY-NC 4.0" required/></label><label className="span-2">Mots-clés<input className="input" name="keywords" placeholder="éducation, intelligence artificielle" required/></label></div><button className="button" type="submit">Créer le brouillon</button></form>;
}
async function sha256(file:File){const buffer=await file.arrayBuffer();return [...new Uint8Array(await crypto.subtle.digest("SHA-256",buffer))].map(v=>v.toString(16).padStart(2,"0")).join("");}
