import type{Prisma}from"@prisma/client";import{db}from"@/lib/db/client";import{logger}from"@/lib/observability/logger";import{cached}from"@/lib/search/cache";import{SEARCH_INDEXES,searchClient}from"@/lib/search/client";import{mapDocument,searchableDocumentInclude}from"@/lib/search/mapper";import{buildFilters,quote,sortRule}from"@/lib/search/query";import type{AcademicSearchDocument,DirectorySearchDocument,SearchQuery,SearchResponse}from"@/lib/search/types";
const facetNames=["universityName","facultyName","departmentName","authorName","language","country","year","category","type","status","license"];
export class SearchService{
 async search(input:SearchQuery){return cached("search",input,()=>this.searchUncached(input),30)}
 private async searchUncached(input:SearchQuery):Promise<SearchResponse>{try{return await this.searchMeili(input)}catch(error){logger.error("meilisearch.fallback",error,{queryLength:input.query.length});return this.searchPostgres(input)}}
 private async searchMeili(input:SearchQuery):Promise<SearchResponse>{const filter=buildFilters(input.filters);const sort=sortRule(input.sort);const started=performance.now();const[documents,directory]=await Promise.all([searchClient().index(SEARCH_INDEXES.documents).search<AcademicSearchDocument>(input.query,{offset:(input.page-1)*input.pageSize,limit:input.pageSize,filter,sort:sort?[sort]:undefined,facets:facetNames,attributesToHighlight:["title","abstract","authorName"]}),searchClient().index(SEARCH_INDEXES.directory).search<DirectorySearchDocument>(input.query,{limit:8,filter:input.filters.country?`country = ${quote(input.filters.country)}`:undefined,sort:input.sort==="alphabetical"?["name:asc"]:undefined})]);return{documents:documents.hits,directory:directory.hits,totalDocuments:documents.estimatedTotalHits??documents.hits.length,totalDirectory:directory.estimatedTotalHits??directory.hits.length,processingTimeMs:Math.round(performance.now()-started),facets:(documents.facetDistribution??{})as Record<string,Record<string,number>>,page:input.page,pageSize:input.pageSize}}
 private async searchPostgres(input:SearchQuery):Promise<SearchResponse>{
  const textFilter:Prisma.DocumentWhereInput=input.query?{OR:[
   {title:{contains:input.query,mode:"insensitive"}},
   {abstract:{contains:input.query,mode:"insensitive"}},
   {author:{name:{contains:input.query,mode:"insensitive"}}},
   {tags:{some:{name:{contains:input.query,mode:"insensitive"}}}},
  ]}:{};
  const where:Prisma.DocumentWhereInput={status:{in:["APPROVED","PUBLISHED"]},deletedAt:null,...postgresFilters(input),...textFilter};
  const orderBy:Prisma.DocumentOrderByWithRelationInput=postgresSort(input.sort);const started=performance.now();const[documents,total]=await db.$transaction([db.document.findMany({where,include:searchableDocumentInclude,orderBy,skip:(input.page-1)*input.pageSize,take:input.pageSize}),db.document.count({where})]);return{documents:documents.map(mapDocument),directory:[],totalDocuments:total,totalDirectory:0,processingTimeMs:Math.round(performance.now()-started),facets:{},page:input.page,pageSize:input.pageSize}}
 async suggestions(query:string){if(query.trim().length<2)return[];const result=await this.search({query:query.trim(),page:1,pageSize:6,sort:"relevance",filters:{}});return[...new Set([...result.documents.map(item=>item.title),...result.directory.map(item=>item.name),...result.documents.flatMap(item=>item.tags)])].slice(0,8)}
 async recentSearches(userId:string,limit=8){const logs=await db.searchLog.findMany({where:{userId},select:{query:true,createdAt:true,resultCount:true},orderBy:{createdAt:"desc"},take:limit*3});return[...new Map(logs.filter(log=>log.query).map(log=>[log.query,log])).values()].slice(0,limit)}
 async popularSearches(limit=8){const rows=await db.searchLog.groupBy({by:["query"],where:{query:{not:""},createdAt:{gte:new Date(Date.now()-30*86400000)}},_count:{query:true},orderBy:{_count:{query:"desc"}},take:limit});return rows.map(row=>row.query)}
}
function postgresFilters(input:SearchQuery):Prisma.DocumentWhereInput{const f=input.filters;const AND:Prisma.DocumentWhereInput[]=[];if(f.university)AND.push({university:{name:f.university}});if(f.faculty)AND.push({faculty:{name:f.faculty}});if(f.department)AND.push({department:{name:f.department}});if(f.author)AND.push({author:{name:f.author}});if(f.language)AND.push({language:f.language});if(f.country)AND.push({university:{country:f.country}});if(f.year)AND.push({year:f.year});if(f.category)AND.push({category:{name:f.category}});if(f.type)AND.push({type:f.type as never});if(f.status)AND.push({status:f.status as never});if(f.license)AND.push({license:f.license});return AND.length?{AND}:{}}
function postgresSort(sort:SearchQuery["sort"]):Prisma.DocumentOrderByWithRelationInput{return({relevance:{publishedAt:"desc"},recent:{publishedAt:"desc"},views:{viewCount:"desc"},downloads:{downloadCount:"desc"},citations:{publishedAt:"desc"},alphabetical:{title:"asc"}}as const)[sort]}
