import { Activity, Building2, CheckCircle2, Clock3, FileText, UserCheck, Users, WalletCards, XCircle } from "lucide-react";
import { AdminShell } from "@/components/admin/admin-shell";
import { db } from "@/lib/db/client";
import { requireAdmin } from "@/lib/auth/guards";

export default async function AdminDashboard() {
  const user = await requireAdmin();
  const [totalUsers,activeUsers,totalDocuments,pendingDocuments,approvedDocuments,rejectedDocuments,institutions,payments,recentUsers,recentDocuments,recentAudit]=await Promise.all([
    db.user.count({where:{status:{not:"DELETED"}}}),db.user.count({where:{status:"ACTIVE"}}),db.document.count({where:{status:{not:"DELETED"}}}),db.document.count({where:{status:"PENDING_REVIEW"}}),db.document.count({where:{status:{in:["APPROVED","PUBLISHED"]}}}),db.document.count({where:{status:"REJECTED"}}),db.university.count(),db.payment.aggregate({where:{status:"SUCCEEDED"},_sum:{amountCents:true}}),db.user.findMany({select:{id:true,name:true,email:true,role:true,status:true,createdAt:true},orderBy:{createdAt:"desc"},take:5}),db.document.findMany({select:{id:true,title:true,status:true,createdAt:true,author:{select:{name:true}}},orderBy:{createdAt:"desc"},take:5}),db.auditLog.findMany({select:{id:true,action:true,entityType:true,createdAt:true,actor:{select:{name:true,email:true}}},orderBy:{createdAt:"desc"},take:8})]);
  const stats=[[Users,totalUsers,"Utilisateurs"],[UserCheck,activeUsers,"Utilisateurs actifs"],[FileText,totalDocuments,"Documents"],[Clock3,pendingDocuments,"En attente"],[CheckCircle2,approvedDocuments,"Validés"],[XCircle,rejectedDocuments,"Rejetés"],[Building2,institutions,"Institutions"],[WalletCards,`${((payments._sum.amountCents??0)/100).toFixed(2)} USD`,"Revenus confirmés"]] as const;
  return <AdminShell user={user}><div className="admin-page"><header className="admin-title"><span className="eyebrow">Vue consolidée</span><h1>Tableau de bord</h1><p>Données opérationnelles calculées directement depuis PostgreSQL.</p></header><section className="admin-stats">{stats.map(([Icon,value,label])=><article className="glass card" key={label}><Icon size={18}/><strong>{value}</strong><span>{label}</span></article>)}</section><section className="admin-dashboard-grid"><article className="glass card admin-panel"><h2>Derniers utilisateurs</h2>{recentUsers.map(item=><div className="admin-row" key={item.id}><span><strong>{item.name??item.email}</strong><small>{item.role} · {item.status}</small></span><time>{item.createdAt.toLocaleDateString("fr-FR")}</time></div>)}</article><article className="glass card admin-panel"><h2>Derniers documents</h2>{recentDocuments.map(item=><div className="admin-row" key={item.id}><span><strong>{item.title}</strong><small>{item.author.name??"Auteur"} · {item.status}</small></span><time>{item.createdAt.toLocaleDateString("fr-FR")}</time></div>)}</article><article className="glass card admin-panel admin-panel-wide"><h2><Activity size={18}/>Activité administrative récente</h2>{recentAudit.map(item=><div className="admin-row" key={item.id}><span><strong>{item.action}</strong><small>{item.actor?.name??item.actor?.email??"Système"} · {item.entityType}</small></span><time>{item.createdAt.toLocaleString("fr-FR")}</time></div>)}</article></section></div></AdminShell>;
}
